services:
  echo_app:
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - DB_CONNECTION=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=15
      - WAIT_SLEEP_INTERVAL=3
    networks:
      - echo-demo-stack

 
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    volumes:
      - database_pg:/var/lib/postgresql/data
    networks:
      - echo-demo-stack


  
  permify:
    image: ghcr.io/permify/permify:latest
    ports:
      - "3476:3476"
      - "3478:3478"
    environment:
      PERSISTENCE: postgres
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres
    networks:
      - echo-demo-stack


volumes:
  database_pg:

networks:
  echo-demo-stack:
    driver: bridge
